<?php include_once('../conexion/conn_bbdd.php'); include_once('../php/ValidaLoginScript.php');include_once('../php/ParametrosClass.php');$DatosWeb =   new ParametrosClass($conexion);include_once('../php/SesionesCookies.php'); ?>
<!DOCTYPE html>
<html lang="es" xml:lang="es" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    
<?php $NumeroCurso = 6;include_once('NewWebEstilosNOIndex.php');include_once('../php/IndexScript.php');include_once('PaginaCursoPHP01.php');  ?>
	
<script>Nombre_correo = 'Eduardo ';
emisorcorreo = 'eduardo.mediavilla@medifestructuras.com';
numCurso = '6';
tituloCurso = 'CURSO NIVEL ESPECIALISTA DE ESTRUCTURA MIXTA CON INTERACCION SUELO ESTRUCTURA PARA USO ADMINISTRATIVO';
precioCurso = 145;
</script><script>DENombre_correo = 'Eduardo ';
DEemisorcorreo = 'eduardo.mediavilla@medifestructuras.com';
</script>

<script  src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script><script  src="../php/VTCursoContenido.js"></script><script  src="../php/VTCursoContenidoCobros.js"></script><script  src="../php/VTCalculoDescuentosCobros.js"></script>   
<title>CURSO NIVEL ESPECIALISTA DE ESTRUCTURA MIXTA CON INTERACCION SUELO ESTRUCTURA PARA USO ADMINISTRATIVO</title>
    
<?php include_once('PaginaCabecera.php');  ?>    
    
	

<script>
 CursorX = 0;
 CursorY = 0;  
 AntiguaY = 0;  
 procesoActivo = 0;
 posY = 0;

function ComprarCurso() {
	
a = document.getElementById("CompraCurso");a.style.display= "none";b = document.getElementById("CorreoGeneral");b.style.display= "none";d    = document.getElementById("CorrreoCobros");posY = d.style.top = CursorY-200;if (posY < 100) { posY = 100;}d.style.top = posY+"px";d.style.display= "block";m = document.getElementById("envoltorioGeneralDescuentos");m.style.display= "none";     
    
}
		

</script>

<?php include_once('PaginaCursoPHP01_2.php');  ?>
</head>

<body onMouseMove="javascript:coordenadas(event);">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TM8DJ4"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

 
<?php include_once('MenuNOIndexCursosVideotutoriales.php');  ?>   
<div class="clear"></div>
<div id="logoPrincipalVideotutoriales"><img src="../imagenes/logos/<?php echo $DatosWeb->GetTrimValor("web_logoblanco") ?>"  alt="medifestructuras.com Logo"></div>

    
    
    
    

<section class="contenedor">
      

 <div class="ficha">  



<?php if ($_SESSION["ver_curso"] == 1) {    include_once('VTCursoCabeceraPago.php'); } else {	  include_once('VTCursoCabeceraNoPago.php'); } ?>


<div class="centro">

<?php include_once('VTCalculoDescuentos.php'); ?> 


</div>
</div><!-- end .ficha ................................................................................ -->
<!--Ficha ............................................................................................ -->
<div class="ficha">
<div class="ficha_fila">  <!--Solicutud de certificado -->


<?php include_once('PaginaCursoPHP02.php'); ?>
</div> <!-- ficha_fila    Solicutud de certificado -->

<div class="ficha_fila">

   <div class = "celda_10_izdaVT"><p class="tituloApartado">Contenido del Curso</p></div>
   <div class = "celda_90_dechaVT"> 
   <div class ="FichaListaFilaRaya"></div>
           
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">PRESENTACIÓN DEL CURSO</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Análisis del edificio</h3><p class ="bloque_descriVT" >Realizaremos un recorrido por el modelo del edificio ya realizado, indicando aquellos puntos donde habrá que poner especial atención para el correcto desarrollo del curso.</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(147)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Análisis general el edificio antes de iniciar el proyecto</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">CONFIGURACIÓN GENERAL</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Datos generales de la obra</h3><p class ="bloque_descriVT" >Realizaremos el inicio de la configuración, empezando por explicar algunas características de los materiales, normativas y algunos apuntes interesantes.</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',110)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/RAR.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Tablas de armado ACI-11 para versiones de CYPE inferiores a la 2020</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',269)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/WORD.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Link video: Tablas de armado ACI-14 </div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',198)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/ZIP.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Tablas de armado ACI-14 para versiones de CYPE superiores o igual a la 2020</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',238)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/RAR.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Tablas de armado 2019 (para versiones software 2021 en adelante, 2022, 2023...)</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(148)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Datos generales de obra configuración inicial</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(588)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Tablas de armado ACI-19 (para versiones de software 2021 en adelante, 2022, 2023...)</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">ESTUDIO GEOTÉCNICO</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Análisis de datos</h3><p class ="bloque_descriVT" >Realizaremos un recorrido por el estudio geotécnico deteniendonos en los puntos importantes. Tomaremos decisiones, resolveremos problemas de cimentación. </p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',58)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Pdf teoría sobre modulo de balasto (extracto)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',59)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/XLS.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Excel Balasto</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(149)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Análisis extenso de datos del suelo suministrado en estudio geotecnico</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Recorrido por la memoria técnica de cypecad</h3><p class ="bloque_descriVT" >Analizaremos la memoria de calculo de cypecad, concretamente la parte referente a la discretización de elementos apoyados en el terreno.</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',56)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Memoria de calculo cypecad teoría de elementos finitos</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(150)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Recorrido por la memoria de calculo de cypecad teoría de elementos finitos con balasto para cimentación </div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">CONFIGURACIÓN DEL PROGRAMA</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Configuración del programa y carga sísmica</h3><p class ="bloque_descriVT" >Configuraremos todo lo necesario y relativo a disposición de armados y carga sísmica aplicada</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(151)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Configuración del botón por posición para el edificio y definición de la carga sísmica</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Configuración estructural</h3><p class ="bloque_descriVT" >Daremos las primeras pautas de diseño para el edificio. Haremos un recorrido por las plantillas DWG</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(152)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Teoría sobre configuración estructural aplicada al edificio visión inicial</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Cargas del edificio</h3><p class ="bloque_descriVT" >Configuraremos las cargas del edificio en base a sus necesidades. Recorreremos las secciones, y veremos cuestiones interesantes.</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',60)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/DWG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Losa 1</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',61)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/DWG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Losa 2</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',62)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/DWG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Losa 3</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(153)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Introducción de cargas al edificio para uso administrativo</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Biblioteca de vigas y espesores mínimos para cumplir compacidad sísmica en pórticos SMF</h3><p class ="bloque_descriVT" >Crearemos nuestras bibliotecas de vigas, cumpliendo las exigencias de compacidad de normativa.</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',57)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/XLS.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Excel compacidad sismica</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(154)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Biblioteca de vigas para el proyecto</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">DEFINICIÓN DE MODELO </h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Definición de vigas de acero</h3><p class ="bloque_descriVT" >Daremos las explicaciones para tener el modelo bien introducido. En los videos anteriores ya introducimos una parte del modelo pero en estos videos terminaremos de definirlo totalmente.</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(155)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Definición de vigas de acero</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(156)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Definición de vigas de acero parte 2</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Definición de vigas T invertidas</h3><p class ="bloque_descriVT" >Introduciremos correctamente la cimentación</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(157)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Definición de vigas T invertidas para cimentación </div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">ANÁLISIS DE ESTABILIDAD GLOBAL</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Análisis sin obtener armado estabilidad global</h3><p class ="bloque_descriVT" >Realizaremos un primer calculo para analizar el comportamiento del conjunto del edificio</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(158)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Análisis sin obtener armado</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Análisis por capacidad y resistencia con énfasis en los requerimientos de columna fuerte viga débil</h3><p class ="bloque_descriVT" >Haremos un pequeño truco de diseño</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(159)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Análisis por capacidad y resistencia de los elementos</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Análisis por capacidad y resistencia junto con ajustes y correcciones</h3><p class ="bloque_descriVT" >Realizamos correcciones al diseño para acercarnos al modelo final, donde todo estará cumpliendo normativa </p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',270)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/WORD.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Link video: Columna fuerte viga-debil</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(160)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Capacidad resistencia y correcciones</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">MEMORIA TÉCNICA DEL PROYECTO</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Memoria técnica del proyecto</h3><p class ="bloque_descriVT" >Haremos un interesante recorrido por la memoria técnica del proyecto, que tendremos que presentar.</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',63)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/WORD.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Memoria técnica del proyecto con interpretación de resultados</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',64)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/WORD.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Fotografías del proyecto</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(161)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Memoria</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">PLANOS FINALES DE EJECUCIÓN DE OBRA</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Planos de ejecución de obra</h3><p class ="bloque_descriVT" >Explicaremos todo lo referente a los planos de ejecucion</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',65)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/DWG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Plano de replanteo</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',84)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/DWG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Plano columnas</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',66)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/DWG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Plano cimentación </div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',68)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/DWG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Plano vigas de acero</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(162)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Planos</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">EDICIÓN FINAL </h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Capacidad y resistencia</h3><p class ="bloque_descriVT" >Realizaremos una edición final de acuerdo a los planos mostrados. Traslapes y ese tipo de cuestiones.</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(163)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Edición de elementos capacidad y resistencia</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(164)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Edición final y obtención definitiva de todo el proyecto</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">VIDEOS DE CORTESIA MEDIFESTRUCTURAS PARA CONFIGURACIÓN GENERAL DEL PROGRAMA</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Videos</h3><p class ="bloque_descriVT" >Videos de cortesia</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(165)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Criterios de ductilidad </div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(166)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Configuración parte 1</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(167)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Configuración parte 2</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(168)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Configuración parte 3</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">NORMATIVA UTILIZADA</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">CAPÍTULOS OFICIALES DE LA NEC </h3><p class ="bloque_descriVT" >En los vídeos constantemente hacemos referencia a la norma, por lo tanto es muy importante que la tengamos a mano. Si bien es cierto que nos centraremos en la Norma Ecuatoriana de la Construcción (NEC), cabe decir que el curso no pretende enfocarse únicamente en una normativa, sino dar solución a una metodología de trabajo. El alumno de otro país podrá solicitar vía email información sobre las exigencias de aprobación de proyectos de su país. Perú, Colombia, México,Bolivia, República Dominicana, Chile, Argentina, Venezuela, Honduras, Guatemala, el Salvador...</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',69)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >NEC_HS_VIDRIO</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',70)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >NEC_SE_AC_(Estructura_Acero)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',71)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >NEC_SE_CG_(cargas_no_sismicas)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',72)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >NEC_SE_CM_(Geotecnia_y_Cimentaciones)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',73)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >NEC_SE_DS_(peligro sismico)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',74)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >NEC_SE_HM_(hormigon_armado)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',75)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >NEC_SE_MD_(estructuras madera)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',76)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >NEC_SE_MP_(mamposteria_estruc)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',77)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >NEC_SE_VIVIENDA</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">EJEMPLO DE PROYECTO</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Ejemplo de planos y memoria</h3><p class ="bloque_descriVT" >Ejemplo</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',91)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/DWG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Planos</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',92)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/WORD.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Memoria en word a modo de ejemplo</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',93)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Memoria en pdf a modo de ejemplo</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">UNIONES</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Uniones<br></h3><p class ="bloque_descriVT" >Realizaremos la explicación para que el alumno resuelva las uniones del curso.</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',109)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PDF.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Memoria de calculo uniones</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(179)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Uniones columna-viga en estructura mixta</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(514)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Aclaración de resolución de unión COLUMNA-VIGA</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(501)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Pernos de anclaje para la placa (procedimiento para prediseño rápido)</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">MATERIAL DE REFUERZO</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Revisión de proyectos</h3><p class ="bloque_descriVT" >Realizaremos la revisión de algunos proyectos reales</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(316)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Revisión de losa de cimentación </div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(317)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Revisión de proyecto Perú</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Trucos de diseño aislados para resolver algunas inquietudes de alumnos</h3><p class ="bloque_descriVT" >Presentaremos trucos aislados para resolver casos específicos solicitados por alumnos que han realizado la totalidad de los cursos de estructuras de medifestructuras.</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(318)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >5 trucos de diseño</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(319)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Trucos de diseño para perfeccionar el dominio del programa</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(322)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Errores del programa, como debemos tratarlos e interpretarlos</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(323)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Memoria de calculo del programa efectos P-delta e interacción suelo</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(324)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Como realizar una viga común, por ejemplo para una rampa</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(325)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Seminario de estructura mixta, aspectos a tener presente</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Respuesta a consultas</h3><p class ="bloque_descriVT" >Daremos respuesta a consultas propuestas por alumnos de medifestructuras</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(320)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Respuesta a consultas sobre losas de cimentación y vigas en T</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(321)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Respuesta a consultas documento word enviado por alumno</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">MATERIAL DE REFUERZO</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/04CursoEstructuraMixta/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Bienvenida al curso</h3><p class ="bloque_descriVT" >El día 25 de junio de 2020 se realizó un seminario online en vivo, donde se habló del planteamiento necesario para poder plantear la profesión de ingeniero estructural a nivel internacional.<br><br>El seminario  puedes visualizarlo antes de iniciar el curso, o después. Indistintamente, pero es necesario que lo visualices para que adquieras el enfoque preciso a la hora de trabajar e interpretar diferentes normativas, y de forma especifica para el curso de estructura mixta con interacción suelo/estructura. Si necesitas algún dato acerca de una normativa especifica, puedes solicitarlo mediante el Foro de la plataforma.<br><br>La única norma que existe es la de utilización individual de usuario. Le deseamos mucha suerte con el avance de su aprendizaje.</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',271)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/WORD.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Seminario Internacional de proyectos</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',272)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/WORD.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Link videos en directo</div><div class='clear'></div><br></div><div class="clear"></div></article>   </div> 
</div> 
</div>

<!-- entrega de certificados (ini) ..............................................................................................-->
<?php include_once('PaginaCursoPHP03.php'); ?><!--entrega de certificados (fin) ..............................................................................................-->




</section><!-- end .contenedor -->
<div id = "CompraCurso">
<img style="cursor:pointer" src="../imagenes/AddToCart_naranja.gif"  alt="Carrito compra" onMouseOut="javascript:GetImagenCart(1,this)" onMouseOver="javascript:GetImagenCart(2,this);AvisoDebeComprar(0)" onclick="javascip:ComprarCurso()"/>

</div>


<div class="centro"> 
   <div id = "CorrreoCobros">    
   <div id = "correoCobrosDatos2" >
   <br>
    <?php if (PresentarDescuento($conexion,$DatosWeb->GetValor("descuento_activo"))) {?> 
   
    <p id="botonCalcular"> <input name="Descuentos" type="button" class ="ButtonGrisnuevo" value ="Calcula tu DESCUENTO por adquirir más de un curso" onClick="javascript:VerDescuentos(1)"/> </p>
   
     <?php } ?>     
           <p class="pide_panPreTit">Comprar el videotutorial</p>
          
        <form  class="formulario">
	    
        <!--<div class="mitad">-->
      <br>
         
       
           <div class = "pide_panPreMensaje"><div class="centro"><script> document.write(tituloCurso.toUpperCase()) </script></div></div> 
           <br><br>
          <div class="clear"></div>
          
          
          <div style="margin-left:10%">
         <label class="pide_panPre">Importe </label> 
         <label class="pide_panPreMensaje">
         	
         	145 <?php  echo $DatosWeb->GetValor("moneda") ?>   

         </label> 
         <div class="clear"></div>
      <label class="pide_panPre">Email </label> <input id = "CBemail" type="text" name="CBemail" size="35" maxlength="99" value= "" required > 
      <br> <br> 
      <label class="pide_panPre">Repita el Email </label> <input id = "CBemail2" type="text" name="CBemail2" size="35" maxlength="99" value= "" required > 
         
         </div>
      <br> 
            
     <div class="clear"></div>
     <br>
       <div class = "pide_panPreMensaje"><div class="centro"><div id = "CBmarcoMensaje" >&nbsp; </div></div></div>
       <br>
     <div class="clear"></div>
  </form>   
     
     <div id= "CBBotones">
         
        <button id = "CBButton1" class="botonVisa" ><img src="../imagenes/Tarjeta_on.gif" alt="Tarjeta Visa" /></button>  

        <!--
           &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;
        <button  id = "CBButton3" class="botonVisa" ><img src="../imagenes/Transfer_on.gif" alt="Transferencia Bancaria" /></button> 
    -->
    
      </div>
       <br>
       <br>
      <div class ="centro"> <input id = "CBButton4" name="Salir" type="button" class ="ButtonGrisP" value ="&nbsp; &nbsp; &nbsp; &nbsp; Salir&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; " /></div>
       <br>
       <br> 
     <div class="clear"></div>
    
 
</div>
   </div> 
   
 </div>   
  <!-- FIN CORREO-->
    <br />
<div class = "Aviso"></div>
    <div class="ficha">
       <?php include_once('PaginaPieNOIndex.php'); ?>    </div>
<?php include_once('PaginaCursoPHP01_4.php');  ?></body>

</html>
   