<?php include_once('../conexion/conn_bbdd.php'); include_once('../php/ValidaLoginScript.php');include_once('../php/ParametrosClass.php');$DatosWeb =   new ParametrosClass($conexion);include_once('../php/SesionesCookies.php'); ?>
<!DOCTYPE html>
<html lang="es" xml:lang="es" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    
<?php $NumeroCurso = 11;include_once('NewWebEstilosNOIndex.php');include_once('../php/IndexScript.php');include_once('PaginaCursoPHP01.php');  ?>
	
<script>Nombre_correo = 'Eduardo ';
emisorcorreo = 'eduardo.mediavilla@cype.com';
numCurso = '11';
tituloCurso = 'CURSO NIVEL ESPECIALISTA EN DISEÑO POR DESEMPEÑO. AENL PUSHOVER';
precioCurso = 145;
</script><script>DENombre_correo = 'Eduardo ';
DEemisorcorreo = 'eduardo.mediavilla@cype.com';
</script>

<script  src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script><script  src="../php/VTCursoContenido.js"></script><script  src="../php/VTCursoContenidoCobros.js"></script><script  src="../php/VTCalculoDescuentosCobros.js"></script>   
<title>CURSO NIVEL ESPECIALISTA EN DISEÑO POR DESEMPEÑO. AENL PUSHOVER</title>
    
<?php include_once('PaginaCabecera.php');  ?>    
    
	

<script>
 CursorX = 0;
 CursorY = 0;  
 AntiguaY = 0;  
 procesoActivo = 0;
 posY = 0;

function ComprarCurso() {
	
a = document.getElementById("CompraCurso");a.style.display= "none";b = document.getElementById("CorreoGeneral");b.style.display= "none";d    = document.getElementById("CorrreoCobros");posY = d.style.top = CursorY-200;if (posY < 100) { posY = 100;}d.style.top = posY+"px";d.style.display= "block";m = document.getElementById("envoltorioGeneralDescuentos");m.style.display= "none";     
    
}
		

</script>

<?php include_once('PaginaCursoPHP01_2.php');  ?>
</head>

<body onMouseMove="javascript:coordenadas(event);">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TM8DJ4"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

 
<?php include_once('MenuNOIndexCursosVideotutoriales.php');  ?>   
<div class="clear"></div>
<div id="logoPrincipalVideotutoriales"><img src="../imagenes/logos/<?php echo $DatosWeb->GetTrimValor("web_logoblanco") ?>"  alt="medifestructuras.com Logo"></div>

    
    
    
    

<section class="contenedor">
      

 <div class="ficha">  



<?php if ($_SESSION["ver_curso"] == 1) {    include_once('VTCursoCabeceraPago.php'); } else {	  include_once('VTCursoCabeceraNoPago.php'); } ?>


<div class="centro">

<?php include_once('VTCalculoDescuentos.php'); ?> 


</div>
</div><!-- end .ficha ................................................................................ -->
<!--Ficha ............................................................................................ -->
<div class="ficha">
<div class="ficha_fila">  <!--Solicutud de certificado -->


<?php include_once('PaginaCursoPHP02.php'); ?>
</div> <!-- ficha_fila    Solicutud de certificado -->

<div class="ficha_fila">

   <div class = "celda_10_izdaVT"><p class="tituloApartado">Contenido del Curso</p></div>
   <div class = "celda_90_dechaVT"> 
   <div class ="FichaListaFilaRaya"></div>
           
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">MARCO NORMATIVO PROCEDIMIENTOS UTILIZADOS (TEORÍA)</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/09Pushover/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Presentación del marco normativo vigente y métodos utilizados.</h3><p class ="bloque_descriVT" >Realizaremos un recorrido por las normativas, para comprender en que fechas fueron creadas y modificadas. Con el fin de comprender la evolución de las técnicas no lineales de evaluación sísmica. </p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',176)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PPT.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Power Point de teoria</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(333)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Presentación de curso y marco normativo</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(334)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Métodos de análisis parte 1 (presentación de métodos)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(335)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Métodos de análisis parte 2 (métodos y categorizacion sísmica)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(336)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Métodos de análisis parte 3  (concepto amortiguamiento)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(337)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Métodos de análisis parte 4 (efectos P-delta y derivas)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(338)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Métodos de análisis parte 5 (derivas, agrietamiento de secciones y tablas FEMA rotulas)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(339)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Métodos de análisis parte 6 (interiorizacion de tablas FEMA- rotulas plásticas)</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/09Pushover/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Ductilidad de elementos y tablas ASCE-41-13</h3><p class ="bloque_descriVT" >Realizaremos un recordatorio sobre el comportamiento del hormigón, donde interiorizaremos aquellos puntos que debe presentar una sección para que su patrón de comportamiento sea dúctil. El objetivo sera que conozcamos los valores que tomara el programa en el momento de realizar la categorizacion de la rotula plástica. </p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',177)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/PPT.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Power Point ductilidad de elementos y tablas ASCE 41-13</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',180)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/JPG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Tabla resumen ductilidad para sistemas estructurales propuesta por ASCE-7-10</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',281)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/WORD.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Criterios de ductilidad de elementos</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(340)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Introducción a la ductilidad de elementos</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(341)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Tablas ASCE-41-13 rotulas secciones de hormigón y de acero</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">CREACIÓN DEL MODELO TRIDIMENSIONAL CON CYPECAD</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/09Pushover/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Modelado del edificio 3D.</h3><p class ="bloque_descriVT" >Realizaremos un modelado de un caso en 3 dimensiones con el programa CYPECAD. Este modelo sera el objeto de análisis de este curso. Con los programas SAP/ETABS propondremos la evaluación de ductilidad y puntos de desempeño. </p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',178)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/DWG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Plantilla autocad para modelo cypecad</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(342)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Modelado del edificio 3d con cypecad</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(343)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Modelado y análisis de errores por falta de ductilidad</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(344)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Evaluación de errores</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">ESTUDIO DE PÓRTICO BIDIMENSIONAL CON SAP</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/09Pushover/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Configuración y modelado con SAP</h3><p class ="bloque_descriVT" >Iniciaremos el bloque considerando las cargas que deberemos de aplicar al pórtico bidimensional, y veremos las primeras configuraciones para el estudio no lineal.</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',179)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/DWG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Armados en vigas</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(345)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Inicio de modelo con SAP</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(346)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Definición de funciones espectrales elásticas e inelasticas.</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(347)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Materiales y secciones (frame sections)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(348)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Secciones y armados colocados en vigas</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/09Pushover/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Definición de casos de carga lineales y no lineales</h3><p class ="bloque_descriVT" >Realizaremos la configuración para todos los casos de carga necesarios. Cgnl, pushover fuerzas y pushover modo 1. Así como otras configuraciones asociadas.</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(349)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Definición de los casos de carga. Load patterns</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(350)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Definición de casos de carga. Combinaciones ASCE 7-10</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(351)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Definición de casos de carga. Obtención de aceros en vigas mediante SAP</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(352)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Definición de casos de carga. Comprobaciones en SAP</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(353)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Definición de casos de carga. Patrón de modo de vibración pushover fuerzas</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/09Pushover/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Definición de rotulas en los elementos y obtención de resultados</h3><p class ="bloque_descriVT" >Realizaremos una definición de rotulas acorde a las tablas del ASCE 41-13. Seguidamente procederemos con el análisis de resultados.</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(354)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Definición de rotulas</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(355)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Obtención de curva de capacidad y inicio de revisiones.</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(356)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Revisión de derivas máximas. Total drift. Y otros requerimientos que solicita la entidad colaboradora.</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(357)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Análisis con el método de los coeficientes/espectro de capacidad</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(358)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Patrón de rotula. Momento rotación.</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">ESTUDIO DE PÓRTICO BIDIMENSIONAL CON ETABS</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/09Pushover/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Modelado y configuraciones</h3><p class ="bloque_descriVT" >Realizaremos el mismo procedimiento que se realizo con SAP, pero esta vez con el programa ETABS. Comenzaremos con la definición geométrica, materiales, elementos y cargas.</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',230)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/JPG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >AVISO/CORRECCIÓN: Video Aceros en vigas y funciones espectrales</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(359)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Presentación de bloque con ETABS</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(360)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Inicio de modelo con ETABS (materiales y secciones)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(361)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Aceros en vigas y funciones espectrales</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(362)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Patrón de carga lateral y definición de load patterns (hipotesis)</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(363)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Casos de cargas lineales y no lineales, definiciones de rotulas y análisis</div><div class='clear'></div><br></div><div class="clear"></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/09Pushover/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Evaluación del modelo </h3><p class ="bloque_descriVT" >Analizaremos a través del método de los coeficientes y del método del espectro de capacidad los puntos de desempeño.</p>
<div class="clear"></div><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(365)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Evaluación sismorresistente acorde a los puntos de desempeño parte 1</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(366)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Evaluación sismorresistente acorde a los puntos de desempeño parte 2</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(367)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Evaluación sismorresistente acorde a los puntos de desempeño parte 3</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">ESTUDIO TRIDIMENSIONAL CON ETABS</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/09Pushover/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Definición del modelo 3d</h3><p class ="bloque_descriVT" >Realizaremos un modelado 3d con todas las precauciones necesarias</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',181)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/JPG.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Gráfica de limitaciones curva Pushover. Fuerza desplazamiento</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(368)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Configuración y modelado parte 1</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(369)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Configuración y modelado parte 2</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(370)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Configuración y modelado parte 3</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(371)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Configuración y modelado parte 4</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(372)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Configuración y modelado parte 5</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(373)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Configuración y modelado parte 6</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(374)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Configuración y modelado parte 7</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(375)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Análisis de resultados parte 1</div><div class='clear'></div><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(376)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Análisis de resultados parte 2</div><div class='clear'></div><br></div><div class="clear"></div></article>
<article><div class = "TituloModulo"><h2 class="modulo_tituloVT">ÚLTIMOS PROYECTOS ENTREGADOS EN LA CONSULTORIA</h2></div>
<div class="celda_5_izdaVT"><img src="../VIDEOTUTORIALES/09Pushover/Prueba_Imagen_bloque_generico.gif" alt="Prueba_Imagen_bloque_generico.gif "></div>
<div class="celda_95_dechaVT"><h3 class="bloque_tituloVT">Proyectos</h3><p class ="bloque_descriVT" >Realizaremos un recorrido por proyectos entregados en la consultoria. Los alumnos profesionales que ya hicieron todos los cursos, podrán ver explicaciones en formato seminario, que les servirá para tener una base de datos de proyectos y situaciones reales. Consideramos que la mejor forma de aprendizaje es a través de ejemplos reales.</p>
<div class="clear"></div><b>Recursos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:Descarga('R',182)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/WORD.gif" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Memoria del proyecto</div><div class='clear'></div><br><b>Videos</b><br /><br /><?php 	  $control = 1;	  $verLinks = 0;                              	  $mostrarCandado = 0;                        	  if ($_SESSION["ver_curso"] == 1) {          		  $verLinks = 1;                          	  } else {                                    		  if ($control == 0) {   			 $verLinks = 1;                       			 $mostrarCandado = 1;                 		  }                                       	  }                                            ?><?php
$txtLinkNO = "javascript:AvisoDebeComprar(25)";$txtLinkSI = "javascript:VerVideo(377)";$txtLink = $txtLinkNO;if( $verLinks == 1) { $txtLink= $txtLinkSI;} ?>
<div  class="bloqueCelda6Inicial"><img src="../imagenes/Punto.gif" alt="Punto capítulo" width="25" height="25" /><img src="../imagenes/Mp4.jpg" alt="Formato fichero" width="25" height="25" /></div><div  class="bloqueCelda88Cursor"  onclick="<?php echo  $txtLink  ?>" onmouseover = "entraReg(this)" onmouseout="salReg(this)" >Seminario de 40 minutos explicación de proyecto entregado en el CAE</div><div class='clear'></div><br></div><div class="clear"></div></article>   </div> 
</div> 
</div>

<!-- entrega de certificados (ini) ..............................................................................................-->
<?php include_once('PaginaCursoPHP03.php'); ?><!--entrega de certificados (fin) ..............................................................................................-->




</section><!-- end .contenedor -->
<div id = "CompraCurso">
<img style="cursor:pointer" src="../imagenes/AddToCart_naranja.gif"  alt="Carrito compra" onMouseOut="javascript:GetImagenCart(1,this)" onMouseOver="javascript:GetImagenCart(2,this);AvisoDebeComprar(0)" onclick="javascip:ComprarCurso()"/>

</div>


<div class="centro"> 
   <div id = "CorrreoCobros">    
   <div id = "correoCobrosDatos2" >
   <br>
    <?php if (PresentarDescuento($conexion,$DatosWeb->GetValor("descuento_activo"))) {?> 
   
    <p id="botonCalcular"> <input name="Descuentos" type="button" class ="ButtonGrisP" value ="Calcula tu DESCUENTO por adquirir más de un curso" onClick="javascript:VerDescuentos(1)"/> </p>
   
     <?php } ?>     
           <p class="pide_panPreTit">Comprar el videotutorial</p>
          
        <form  class="formulario">
	    
        <!--<div class="mitad">-->
      <br>
         
       
           <div class = "pide_panPreMensaje"><div class="centro"><script> document.write(tituloCurso.toUpperCase()) </script></div></div> 
           <br><br>
          <div class="clear"></div>
          
          
          <div style="margin-left:10%">
         <label class="pide_panPre">Importe </label> 
         <label class="pide_panPreMensaje">
         	
         	145 <?php  echo $DatosWeb->GetValor("moneda") ?>   

         </label> 
         <div class="clear"></div>
      <label class="pide_panPre">Email </label> <input id = "CBemail" type="text" name="CBemail" size="35" maxlength="99" value= "" required > 
      <br> 
      <label class="pide_panPre">Repita el Email </label> <input id = "CBemail2" type="text" name="CBemail2" size="35" maxlength="99" value= "" required > 
         
         </div>
      <br> 
            
     <div class="clear"></div>
     <br>
       <div class = "pide_panPreMensaje"><div class="centro"><div id = "CBmarcoMensaje" >&nbsp; </div></div></div>
       <br>
     <div class="clear"></div>
  </form>   
     
     <div id= "CBBotones">
         
        <button id = "CBButton1" class="botonVisa" ><img src="../imagenes/Tarjeta_on.gif" alt="Tarjeta Visa" /></button>  

        <!--
           &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;
        <button  id = "CBButton3" class="botonVisa" ><img src="../imagenes/Transfer_on.gif" alt="Transferencia Bancaria" /></button> 
    -->
    
      </div>
       <br>
       <br>
      <div class ="centro"> <input id = "CBButton4" name="Salir" type="button" class ="ButtonGrisP" value ="&nbsp; &nbsp; &nbsp; &nbsp; Salir&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; " /></div>
       <br>
       <br> 
     <div class="clear"></div>
    
 
</div>
   </div> 
   
 </div>   
  <!-- FIN CORREO-->
    <br />
<div class = "Aviso"></div>
    <div class="ficha">
       <?php include_once('PaginaPieNOIndex.php'); ?>    </div>
<?php include_once('PaginaCursoPHP01_4.php');  ?></body>

</html>
   